name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 18

      # - name: Install dependencies
      #   run: yarn install --frozen-lockfile

      # - name: Build
      #   run: yarn build

      # # Semantic release, publish to image Docker Hub.

      # - name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: yarn release

      # # ------------------

      # # Docker build and publish to Github Container Registry

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/aolde/lametric-nightscout-proxy:latest
